# fly.toml app configuration file generated for bibliogame-shy-sun-9509 on 2025-08-07T17:49:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bibliogame-shy-sun-9509"
primary_region = "otp"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  processes = ["app"]

[processes]
  app = "gunicorn project_settings.wsgi:application --bind 0.0.0.0:8080 --workers 2"
