# Generated by Django 5.2.3 on 2025-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatars/default_avatar.png', upload_to='static/avatars/'),
        ),
    ]
