# Generated by Django 5.2.3 on 2025-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliogames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
