# Generated by Django 5.2.3 on 2025-07-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliogames', '0004_alter_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на гру'),
        ),
    ]
