# Generated by Django 5.2.3 on 2025-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliogames', '0005_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(default='www.example.com'),
            preserve_default=False,
        ),
    ]
